tab = int(input("Digite um numero para ver sua tabuada: "))
print("-" * 15)
print(f"{tab} X {1:2} = {tab*1}")
print(f"{tab} X {2:2} = {tab*2}")
print(f"{tab} X {3:2} = {tab*3}")
print(f"{tab} X {4:2} = {tab*4}")
print(f"{tab} X {5:2} = {tab*5}")
print(f"{tab} X {6:2} = {tab*6}")
print(f"{tab} X {7:2} = {tab*7}")
print(f"{tab} X {8:2} = {tab*8}")
print(f"{tab} X {9:2} = {tab*9}")
print(f"{tab} X {10:2} = {tab*10}")
print("-" * 15)

# Programa simples que faz a tabuada do numero digitado pelo usuario! 